<a href="https://colab.research.google.com/github/AdamekMateusz/ML_bc/blob/main/supervised/podstawy/11_20_cwiczenia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


## 11-20 Ćwiczenia

### Ćwiczenie 11
Zbuduj jednowymiarową tablicę *numpy* składającą się z wszystkich liczb dwucyfrowych. Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.arange()*.

**Oczekiwany wynik:**
```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
 ```

In [4]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### Ćwiczenie 12
Zbuduj tablicę *numpy* określoną poniżej:
```
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
```
Zwróć uwagę, że kształt tablicy to (9, 10). Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.arange()* i metody *np.ndarray.reshape()*.

In [5]:
A=np.arange(10,100).reshape((9,10))
print(A)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### Ćwiczenie 13
Zbuduj dwuwymiarową tablicę *numpy* o kształcie 6x6 - macierz jednostkowa o typie danych *int*. Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.eye()*.

**Oczekiwany wynik:**
```
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
 ```

In [6]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Ćwiczenie 14
Ustaw ziarno losowe na 10. Następnie zbuduj jednowymiarową tablicę *numpy* składającą się z 30 pseudolosowo wygenerowanych wartości z rozkładu jednostajnego na przedziale [0,1). Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.random.rand()*.

**Oczekiwany wynik:**
```
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 ```

In [8]:
np.random.seed(10)
A=np.random.rand(30)
print(A)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


### Ćwiczenie 15
Ustaw ziarno losowe na 20. Następnie zbuduj dwuwymiarową tablicę *numpy* o kształcie (10, 4) z wygenerowanymi pseudolosowo wartościami ze standardowego rozkładu normalnego N(0,1).

**Wskazówka:** Użyj funkcji *np.random.randn()*.

**Oczekiwany wynik:**
```
[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]
 ```

In [15]:
np.random.seed(20)
A=np.random.normal(0,1,40)
A=A.reshape((10,4))
print(A)

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


### Ćwiczenie 16
Ustaw ziarno losowe na 30. Następnie zbuduj dwuwymiarową tablicę *numpy* o kształcie (10, 4) z wygenerowanymi pseudolosowo wartościami z rozkładu normalnego N(100, 5).

**Wskazówka:** Użyj funkcji *np.random.randn()*.

**Oczekiwany wynik:**
```
[[ 97.17349231 103.41650023  97.82942436 101.05220329]
 [ 99.7748353  100.67930221  96.14063068 103.544381  ]
 [100.30029631  97.52499594 103.52901961 100.24037271]
 [ 98.29153712  98.2666258  103.09437633 101.70027274]
 [ 99.36127721 101.20382627  95.34026547 102.09694365]
 [ 99.98708001  98.95468525  99.05410904 102.38025432]
 [ 93.50787269 103.61547679 103.18753701  98.51356237]
 [102.20256689  96.19764407  97.54000366  97.05813038]
 [101.81233513  97.66380453  98.45883627  98.09317768]
 [102.48979932  95.70413391  98.43161651 101.89861815]]
 ```

In [38]:
np.random.seed(30)
A=np.ndarray((10,4))
a=np.shape(A)
#print(a)
B=np.random.normal(100,5,a[0]*a[1])
B=B.reshape((a[0],a[1]))
print(B)

#print(A)

[[ 93.67973668 107.63952676  95.14644531 102.35279808]
 [ 99.49651642 101.51896592  91.37018786 107.92547685]
 [100.67148297  94.46572267 107.89112775 100.53748971]
 [ 96.17976087  96.12405745 106.91923583 103.80192542]
 [ 98.57177243 102.69183738  89.58051684 104.68890855]
 [ 99.97111002  97.66260516  97.8849235  105.32241047]
 [ 85.48316202 108.08445187 107.12754943  96.67622441]
 [104.9250893   91.49767367  94.49928096  93.42177955]
 [104.05250455  94.77610813  96.55385313  95.73621568]
 [105.56736054  90.39415141  96.49298791 104.24543925]]


### Ćwiczenie 17
Dokonaj iteracji po tablicy *numpy* A i wydrukuj każdy element tablicy do konsoli.
```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```
**Wskazówka:** Użyj funkcji *np.nditer()*.

**Oczekiwany wynik:**
```
1
4
3
5
2
6
```

In [68]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])

for i in np.nditer(A):
  print(i)

1
4
3
5
2
6


### Ćwiczenie 18
Utwórz jednowymiarową tablicę *numpy* (wektor) składającą się z 11 równo rozmieszczonych punktów z przedziału [0,1]. Wynik wydrukuj do konsoli.

**Wskazówka:** Użyj funkcji *np.linspace()*.

**Oczekiwany wynik:**
```
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
```

In [41]:
#rowno rozmieszczone 11 puntkow
np.linspace(0,1,11)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Ćwiczenie 19
Ustaw ziarno losowe na 42. Wygeneruj jednowymiarową tablicę (wektor) zawierającą możliwy wynik gry w Duży Lotek. Wynik wydrukuj do konsoli.

**Wskazówka:** Wynikiem gry jest 6-elementowy wektor wartości od 1 do 49 włącznie wartości wylosowanych bez powtórzeń.

**Oczekiwany wynik:**
```
[39 29 15 43  8 21]
```

In [53]:
np.random.seed(42)
a=np.random.randint(low=1, high=50, size=6)
print(a)

[39 29 15 43  8 21]


### Ćwiczenie 20
Zbuduj dwuwymiarową tablicę o kształcie 6x6 poniżej:
```
[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
```
**Wskazówka:** Użyj funkcji *np.diag()*.

In [52]:
a=np.arange(6)
b=np.diag(a)
print(b)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
