<a href="https://colab.research.google.com/github/AdamekMateusz/ML_bc/blob/main/supervised/podstawy/21_30_cwiczenia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 21-30 Ćwiczenia

In [75]:
import numpy as np

### Ćwiczenie 21
Wygeneruj następującą tablicę *numpy*.
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Następnie zapisz tablicę do pliku binarnego o nazwie `array.npy`, załaduj ten plik z powrotem do innej zmiennej i wydrukuj jej zawartość do konsoli.

**Wskazówka:** Użyj funkcji *np.save()* oraz *np.load()*.

In [76]:
A=np.arange(12).reshape(3,4)
with open('array.npy', 'wb') as f:
    np.save(f, A)

with open('array.npy', 'rb') as f:
  a=np.load(f)

print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Ćwiczenie 22
Wygeneruj następującą tablicę *numpy*:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Zapisz tablicę do pliku tekstowego o nazwie `array.txt` z dwoma miejscami po przecinku, załaduj plik z powrotem do innej zmiennej i wydrukuj jej zawartość do konsoli.

**Wskazówka:** Użyj funkcji *np.savetxt()* oraz *np.loadtxt()*.

In [77]:
B=np.linspace(0,11,12).reshape(3,4)
c=np.savetxt("array.txt",B,fmt='%10.2f')
a=np.loadtxt("array.txt")
print(a)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


### Ćwiczenie 23
Wygeneruj i przekształć następującą tablicę *numpy* na listę:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj metody *np.array.tolist()*.

**Oczekiwany wynik:**
```
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
```

In [78]:
A=np.linspace(0,11,12).reshape((3,4)).astype(int)
list1=A.tolist()
print(list1)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


### Ćwiczenie 24
Podana jest następująca tablica *numpy*:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Używając operatora wycinania przekształć tablicę w następujący sposób:

zamień wiersze (pierwszy z ostatnim)
```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```
Wydrukuj wynik do konsoli.

**Oczekiwany wynik:**
```
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
```

In [79]:
A=np.linspace(0,11,12).reshape((3,4))
A[[2, 0],:] = A[[0, 2],:] 

print(A)

[[ 8.  9. 10. 11.]
 [ 4.  5.  6.  7.]
 [ 0.  1.  2.  3.]]


### Ćwiczenie 25
Następującą tablicę numpy:
```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
przekształć w tablicę poniżej:
```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```
Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.pad()*.

**Oczekiwany wynik:**
```
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
```

In [80]:
A=np.ones(shape=(4,4))
A=np.pad(A,(1,1),'constant',constant_values=(0,0))
print(A)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Ćwiczenie 26
Następującą tablicę *numpy*:
```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```
przekształć w tablicę poniżej:
```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```
Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj operatora wycinania i przypisz odpowiednie wartości.

**Oczekiwany wynik:**
```
[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]
```

In [81]:
#A=np.linspace(0,35,36).reshape((6,6))
A=np.zeros((6,6))
#print(A[:,0]) #tak wydrukuje pierwsza kolumne
for x in range(0,6,2):
  A[:,x]=np.array([10,5,10,5,10,5])
 
print(A) 

[[10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]
 [10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]
 [10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]]


### Ćwiczenie 27
Połącz tablice A i B w jedną tak jak pokazano poniżej. Wydrukuj wynik do konsoli.
```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```
**Wskazówka:** Użyj funkcji *np.append()*.

**Oczekiwany wynik:**
```
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]
 ```

In [85]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

np.append(A,B,axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### Ćwiczenie 28
Z podanych tablic A i B poniżej, wyodrębnij wspólne elementy (przecięcie) tablic. Wydrukuj wynik do konsoli.
```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```
**Wskazówka:** Użyj funkcji *np.intersect1d()*.

**Oczekiwany wynik:**
```
[0 2 3]
```

In [92]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])   

np.intersect1d(A,B)

array([0, 2, 3])

### Ćwiczenie 29
Podano następującą tablicę *numpy* A. Znajdź unikalne wartości tej tablicy. Wydrukuj wynik do konsoli.
```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```
**Wskazówka:** Użyj funkcji *np.unique()*.

**Oczekiwany wynik:**
```
[1 2 4 5 7 9]
```

In [93]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

np.unique(A)

array([1, 2, 4, 5, 7, 9])

### Ćwiczenie 30
Podana jest poniższa tablica:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Zwróć indeksy z maksymalnymi wartościami dla danego wiersza. Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.argmax()*.

**Oczekiwany wynik:**
```
[0 2 1]
```

In [99]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

#A[:,0] tak zwraca caly wiersz
for x in range(np.shape(A)[0]):
  print(np.argmax(A[:,x]))

print(np.argmax(A, axis=1))

0
2
1
[0 2 1]
