<a href="https://colab.research.google.com/github/AdamekMateusz/ML_bc/blob/main/supervised/podstawy/Copy_of_31_40_cwiczenia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 31-40 Ćwiczenia

### Ćwiczenie 31
Posortuj tablicę A poniżej:

* według wiersza (rosnąco)
* według kolumny (rosnąco)
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.sort()*.

**Oczekiwany wynik:**
```
[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]
```

In [ ]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
np.sort(A,axis=1) #wedlug wiersza
np.sort(A,axis=0) #wedlug kolumny

array([[ 1.99,  2.39,  4.99],
       [ 4.99,  3.49,  7.29],
       [14.99,  9.99,  9.99]])

### Ćwiczenie 32
Wyodrębnij wszystkie elementy tablicy A o wartości większej niż 8. Wydrukuj wynik do konsoli.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```
**Oczekiwany wynik:**
```
[ 9.99  9.99 14.99]
```

In [ ]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
A[A>8] #wuswietlam wartosci wieksze od 8

array([ 9.99,  9.99, 14.99])

### Ćwiczenie 33
Podana jest następująca tablica A. Zastąp elementy większe niż 10 wartością stałą 10.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.where()*.

**Oczekiwany wynik:**
```
[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]
```

In [ ]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
np.where(A>10,10,A) #jesli wartosc wieksza od 10 zastepuje 10 jesli nie to pozostawia taka jaka byla

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

### Ćwiczenie 34
Przedstaw poniższą dwuwymiarową tablicę A jako 'spłaszczoną' jednowymiarową tablicę. Wydrukuj wynik do konsoli.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
**Wskazówka:** Użyj funkcji *np.ravel()*.

**Oczekiwany wynik:**
```
[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]
```

In [ ]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
print(A.reshape((-1)))
print(A.ravel())

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]
[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


### Ćwiczenie 35
Zbuduj tablicę o tym samym kształcie i typie danych co tablica A i wypełnij ją stałą wartością 0.0. Wydrukuj wynik do konsoli.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
**Wskazówka:** Użyj funkcji *np.zeros_like()*.

**Oczekiwany wynik:**
```
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 ```

In [ ]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
B=np.full((np.shape(A)),0,dtype=np.float)
print(B)

C=np.zeros_like(A)
print(C)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Ćwiczenie 36
Zbuduj tablicę o tym samym kształcie i typie danych co tablica A i wypełnij ją stałą wartością 9.99. Wydrukuj wynik do konsoli.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
**Wskazówka:** Użyj funkcji *np.full_like()*.

**Oczekiwany wynik:**
```
[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]
 ```

In [1]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
np.full_like(A,9.99)

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

### Ćwiczenie 37
Zbuduj dwuwymiarową tablicę (macierz dolna trójkątna) poniżej:
```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
Wydrukuj wynik do konsoli.

**Wskazówka:** Użyj funkcji *np.tri()*.

**Oczekiwany wynik:**
```
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
```

In [2]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

### Ćwiczenie 38
Utwórz dowolną trójwymiarową tablicę o kształcie (2, 3, 4) i przypisz do zmiennej A. Wystarczy tylko zdefiniować tablicę A.

**Przykład:**
```
[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]

 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]
```

In [4]:
import numpy as np


A = np.full((2,3,4),[1,2,3,4])
print(A)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


### Ćwiczenie 39
Wygeneruj dwuwymiarową tablicę o kształcie (200, 300) wypełnioną losowymi wartościami od 0 do 255 (włącznie) o typie danych *np.uint8* i przypisz do zmiennej *image*.

In [6]:
image=np.random.randint(low=0,high=255,size=60000,dtype=np.uint8).reshape((200,300))

### Ćwiczenie 40
Tablica *image* jest podana poniżej:
```
image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)
```
Posortuj tablicę *image* wzdłuż wiersza rosnąco i przypisz do zmiennej *image_sorted*.

In [12]:
import numpy as np


image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)
imaged_sorted=np.sort(image)
print(imaged_sorted)

[[  0   1   2 ... 254 255 255]
 [  1   2   3 ... 252 253 254]
 [  0   0   1 ... 253 253 254]
 ...
 [  0   1   1 ... 252 254 255]
 [  0   0   0 ... 252 253 253]
 [  0   0   0 ... 251 252 254]]
