<a href="https://colab.research.google.com/github/AdamekMateusz/ML_bc/blob/main/supervised/podstawy/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importujemy nasze biblioteki

In [57]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'0.22.2.post1'

In [58]:
data={
    'size':['XL','L',"M","L",'M'],
    'color':['red','green','blue','green','red'],
    'gender':['female','male','male','female','female'],
    'price':[199.0,89.0,99.0,129.0,79.0],
    'weight':[500,450,300,380,410],
    'bought':['yes','no','yes','no','yes']

}

df_raw=pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

Tworzenie kopi naszych danych

In [59]:
df=df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


Zmiana typu danych i wstepna eksploaracja

In [60]:
#tworzymy petle w ktorej bedziemy przechodzic po slowniku

for col in ['size','color','gender','bought']:
  #chcemy zmienic ich typ na typ category
    df[col]=df[col].astype('category')
df['weight']=df['weight'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 628.0 bytes


In [61]:
df.describe()
#domyslnie wyswietla tylko statystyki dla kolumn numerycznych

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [62]:
df.describe().T


count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [63]:
df.describe(include=['category']).T
#pozwoli nam wyswietlic dodatkowe elementy dotyczace zmiennej category

count unique     top freq
size       5      3       M    2
color      5      3     red    2
gender     5      2  female    3
bought     5      2     yes    3

In [64]:
df


size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

Label Encoder, bedziemy chcieli przemapowac nasze zmienne, czy bedziemy chcieli uzyskac je w postaci danych liczbowych

In [65]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le.fit(df['bought']) #metoda fit dopasuje nasz encoder do zmiennej 'bought'
le.transform(df['bought'])  #przetransformujemy nasza zmienna bought

array([1, 0, 1, 0, 1])

In [66]:
le.fit_transform(df['bought']) #jest rownoznancze z tym zapisem powyzej

array([1, 0, 1, 0, 1])

In [67]:
#pokaze jak wyglada nasze mapowanie
le.classes_

array(['no', 'yes'], dtype=object)

In [68]:
df['bought']=le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [69]:
#ta klasa jest stosowana do przeksztalcania, ale nie do kodowania zmiennych kategorycznych
df['bought']=le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [70]:
from sklearn.preprocessing import OneHotEncoder

#domyslnie zwraca macierz żadką (gdy  nie damy paramatru sparse)
encoder=OneHotEncoder(sparse=False)
encoder.fit(df[['size']])

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)

In [71]:
encoder.transform(df[['size']])

#mamy 5 wierszy i mamy 3 unikalne wartosci w kolummnie size (M,L,XL)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [72]:
encoder.categories_
#wyswietli nam to ktora kolmna jest przypisanana do ktorego typu

[array(['L', 'M', 'XL'], dtype=object)]

In [73]:
#aby pozbyc sie problemu z liniowoscia danych nalezy wykonac to w nastepujacy sposob
#dodajemy parametr drop
encoder=OneHotEncoder(drop='first', sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']]) 

#rezuttatem beda dwie kolumny (n-1 kolumn)

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

Pandas i funkcj get_dummies()

In [74]:
pd.get_dummies(data=df)
#problem kodowania zero jedynkowego, czyli jedna z tych kolumn daje nam ta sama informacje co druga tutaj kolumna bought no , i bought yes

price  weight  size_L  ...  gender_male  bought_no  bought_yes
0  199.0   500.0       0  ...            0          0           1
1   89.0   450.0       1  ...            1          1           0
2   99.0   300.0       0  ...            1          0           1
3  129.0   380.0       1  ...            0          1           0
4   79.0   410.0       0  ...            0          0           1

[5 rows x 12 columns]

In [75]:
pd.get_dummies(data=df,drop_first=True)
#zapobiega to powielaniu sie danych 

price  weight  size_M  ...  color_red  gender_male  bought_yes
0  199.0   500.0       0  ...          1            0           1
1   89.0   450.0       0  ...          0            1           0
2   99.0   300.0       1  ...          0            1           1
3  129.0   380.0       0  ...          0            0           0
4   79.0   410.0       1  ...          1            0           1

[5 rows x 8 columns]

In [76]:
pd.get_dummies(data=df, drop_first=True, prefix='new')

price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0      0       1          0        1         0        1
1   89.0   450.0      0       0          1        0         1        0
2   99.0   300.0      1       0          0        0         1        1
3  129.0   380.0      0       0          1        0         0        0
4   79.0   410.0      1       0          0        1         0        1

In [77]:
pd.get_dummies(data=df, drop_first=True, prefix='new',prefix_sep="-")

price  weight  new-M  new-XL  new-green  new-red  new-male  new-yes
0  199.0   500.0      0       1          0        1         0        1
1   89.0   450.0      0       0          1        0         1        0
2   99.0   300.0      1       0          0        0         1        1
3  129.0   380.0      0       0          1        0         0        0
4   79.0   410.0      1       0          0        1         0        1

In [78]:
pd.get_dummies(data=df, drop_first=True, prefix='new',columns=['size'])
#zakodujemy tylko wybrane kolumny

color  gender  price  weight bought  new_M  new_XL
0    red  female  199.0   500.0    yes      0       1
1  green    male   89.0   450.0     no      0       0
2   blue    male   99.0   300.0    yes      1       0
3  green  female  129.0   380.0     no      0       0
4    red  female   79.0   410.0    yes      1       0

###Standaryzacja danych

Skupimy sie na zmiennych numerycznych w celu ich wystandaryzowania, znaczenie ma ich rozrzut, 

Estymatory Wariancji,

std() -pandas nieobciazonyny, estymator wariancji zaimplementowany jako nieobciazony

std() -numpy , estymator zaimplementowany jako obciazony

In [81]:
print(f"{df['price']}\n")
print(f"Srednia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Srednia: 119.0
Odchylenie standardowe: 48.4768


In [82]:
(df['price']-df['price'].mean())/df['price'].std()


0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [83]:
def standarize(x):
  return (x-x.mean())/x.std()

standarize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [84]:
#funckja taka jest terz zaimplementowana w tej bibliotece
from sklearn.preprocessing import scale

scale(df['price'])
#mozna zauwazcy ze wartsoci sie roznia gdyz jest to roznica estymatora obicazonego i nieobciazonego wariancji

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [85]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

#pozwoli nam ta funckja w łatwiejszy sposob zachowac dane oraz je rozszerzcy

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [89]:
scaler=StandardScaler()
df[['price','weight']]=scaler.fit_transform(df[['price','weight']])
df
#pozwoli nam to wystandarzyowaca dwie kolumny price i weight

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

Przygotowanie danych do modelu

In [90]:
df=df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [94]:
le=LabelEncoder()
#zamianiamy nasze yes i no na wartosci 1 i 0
df['bought']=le.fit_transform(df['bought'])

#standaryzujemy nasze dane
scaler=StandardScaler()
df[['price','weight']]=scaler.fit_transform(df[['price','weight']])

#konwertujemy doi spostaci binarnej pozostala zawasrtosc tabelki
df=pd.get_dummies(data=df,drop_first=True)
df

price    weight  bought  ...  color_green  color_red  gender_male
0  1.845062  1.366002       1  ...            0          1            0
1 -0.691898  0.623610       0  ...            1          0            1
2 -0.461266 -1.603567       1  ...            0          0            1
3  0.230633 -0.415740       0  ...            1          0            0
4 -0.922531  0.029696       1  ...            0          1            0

[5 rows x 8 columns]